// SETTINGS REDUCER ACTIONS
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
export const SET_LOADING = 'SET_LOADING';

// MODAL REDUCER ACTIONS
export const SET_MODAL = 'SET_MODAL';

// POKEMON REDUCER ACTIONS
export const SET_POKEMON = 'SET_POKEMON';
